{
 "title": "MAC Network Monitor ",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Allowed Devices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "network_allowed_devices_seen", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rogue Devices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "network_rogue_devices_seen", "legendFormat": "__auto" }
   ]
  },
  { "title": "Active Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 } },
  {
   "title": "Network Devices Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "network_device_events_total", "legendFormat": "__auto" }
   ]
  }
 ]
}